WHy this error in my console? The secoond error appeared while I tried to add a finance option
input.tsx:8 A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://react.dev/link/controlled-components
<input>
_c	@	input.tsx:8
<Input>
render	@	page.tsx:312
<Controller>
FormField	@	form.tsx:39
<FormField>
CalculatorPage	@	page.tsx:305
await in fetchServerResponse
onClick	@	Header.tsx:67
page.tsx:228 Error submitting finance option:  FirebaseError: Function addDoc() called with invalid data. Unsupported field value: undefined (found in field insuranceRatePercentage in document financeOptions/ilBPJXohKBUTBDhem9Jm)
error	@	intercept-console-error.ts:41
onSubmit	@	page.tsx:228
await in onSubmit
(anonymous)	@	createFormControl.ts:1195
await in (anonymous)
executeDispatch	@	react-dom-client.development.js:16426
runWithFiberInDEV	@	react-dom-client.development.js:1510
processDispatchQueue	@	react-dom-client.development.js:16476
(anonymous)	@	react-dom-client.development.js:17074
batchedUpdates$1	@	react-dom-client.development.js:3253
dispatchEventForPluginEventSystem	@	react-dom-client.development.js:16630
dispatchEvent	@	react-dom-client.development.js:20716
dispatchDiscreteEvent	@	react-dom-client.development.js:20684